version: '3'
services:
  nginx-server:
    container_name: nginx-server
    restart: always
    build:
      dockerfile: dev.Dockerfile
      context: nginx
    volumes:
      - ./nginx/logs:/var/log/nginx
    ports:
      - '80:80'

  react-front:
    container_name: react-front
    build:
      dockerfile: dev.Dockerfile
      context: front
    env_file:
       - .env
    volumes:
      - /usr/app/node_modules
      - ./front:/usr/app
    command: ["npm", "run", "start"]

  node-back:
    container_name: node-back
    build:
      context: back
      dockerfile: dev.Dockerfile
    env_file:
       - .env
    volumes:
      - /usr/app/node_modules
      - ./back:/usr/app
    command: ["npm", "run", "start"]

  mongo:
    container_name: mongo-db
    build:
      context: ./mongDb
      dockerfile: dev.Dockerfile
    restart: always
    env_file:
       - .env
    volumes:
      - mongo-data:/data/db

  postgres:
    container_name: postgres-db
    build:
      context: ./postgresDb
      dockerfile: dev.Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
  mongo-data:
    driver: local