version: '3'

networks:
  daily-network:
    driver: bridge

services:
  node-back1:
    container_name: node-back1
    ports: 
      - '4000:4000'
    networks:
      - daily-network
    image: ${DOCKER_USER_ID}/daily:${BUILD_NUMBER}
    
    volumes:
      - .:/code
    command: ["npm", "start"]
    
  # node-back2:
  #   container_name: node-back2
  #   ports: 
  #     - '4001:4000'
  #   networks:
  #     - daily-network
  #   build:
  #     context: .
  #     dockerfile: ./dev.Dockerfile
  #   env_file:
  #      - .env
  #   volumes:
  #     - /usr/app/node_modules
  #     - ./:/usr/app
  #   command: ["npm", "start"]

  postgres:
    image: postgres
    container_name: postgres-db
    restart: unless-stopped
    ports: 
      - '5432:5432'
    networks:
      - daily-network
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - '8001:80'
    networks:
      - daily-network
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    env_file:
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
   

volumes:
  postgres-data:
  pgadmin-data:
